version: '3.0'

services:
  prms-backend: 
    container_name: prms-backend
    image: prms-backend-image
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/code:/home/gradle/src
      - ./backend/vscode:/root/.vscode-server
    ports:
      - 9002:9002 
      - 9003:9003
    networks:
      - prmsnet 
  prms-forntend: 
    container_name: prms-forntend
    image: prms-forntend-image
    build: 
      context: ./forntend
      dockerfile: Dockerfile
    depends_on:
      - prms-backend
    volumes:
      - ./forntend/vscode:/root/.vscode-server
      - ./forntend/code:/app
    ports:
      - 4041:5000
    networks:
      - prmsnet 
networks: 
  prmsnet: